% Facts
nextday(1,2). nextday(2,3). nextday(3,4). nextday(4,5).
nextroom(1,2). nextroom(2,3). nextroom(3,4).
course(c1,1,1). course(c1,4,1).
course(c2,1,2). course(c2,1,3). course(c2,2,1). course(c2,2,2).
course(c3,3,2). course(c3,3,4). course(c3,4,2). course(c3,4,3).
course(c4,4,4). course(c4,5,2). course(c4,5,3). course(c4,5,4).
sumdays(1,2). sumdays(2,2). sumdays(3,2). sumdays(4,2).
sumrooms(1,1). sumrooms(2,2). sumrooms(3,1). sumrooms(4,3). sumrooms(5,2).

% Solution:
% { scheduled(1,1), scheduled(2,1), scheduled(2,2), scheduled(3,4), scheduled(4,2), scheduled(4,3), scheduled(4,4), scheduled(5,2), scheduled(5,3) }
% { scheduled(1,3), scheduled(2,1), scheduled(2,2), scheduled(3,4), scheduled(4,1), scheduled(4,2), scheduled(4,4), scheduled(5,2), scheduled(5,3) }
% { scheduled(1,2), scheduled(2,1), scheduled(2,2), scheduled(3,4), scheduled(4,1), scheduled(4,2), scheduled(4,3), scheduled(5,3), scheduled(5,4) }